### PR TITLE
New problems

### PR DESCRIPTION
**Pull request by ImogenBits**
Adjusts the pairsum and biclique problem to work with the new Problem classes. Note that I didn't modify the docs for the biclique problem so they now are massively inaccurate.

### CODE REVIEW

**Comment by Benezivas** [comment]
Could you please demonstrate how to adapt the new module structure regarding the tests? We will be able to throw most of the original parser tests away, as it makes sense to write generic tests for specific `ProblemModel`s, such as `DirectedGraph`.

It would be nice (and sufficient) if you could adapt a few of the old tests for the verifier of the `biclique` problem, I should then be able to adapt the remaining test cases.

**Comment by ImogenBits** [comment]
all problems are updated now

**Comment by ImogenBits** [comment]
Updated them, you need to manually approve them to run

**Comment by Benezivas** [comment]
Thank you, I have also adjusted workflows to be manually triggered only for new Accounts.

**Review by Benezivas — APPROVED** [review]

**Pull request merged**
